server:
  port: 8080
spring:
  application:
    name: Document Management API

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/document_management_db
    username: admin_user
    password: password
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show-sql: true


  flyway:
    baseline-on-migrate: true
    default-schema: public
    schemas: public
    baseline-version: 0


  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
  web:
    resources:
      static-locations: classpath:/static/uploads/


  # JWT token properties for authentication and authorization
app:
  jwt:
    secret: "77397A24432646294A404E635266556A586E327235753878214125442A472D4B"
    expiration-in-ms: 86400000  # JWT expiration time in milliseconds (24 hours)

    # Internal API key for authentication purposes
  authentication:
    internal-api-key: InternalApiKey1234!