server:
    port: 8080

spring:
    application:
        name: Document Management API

# Database Configuration
    datasource:
        url: jdbc:postgresql://localhost:5432/document_management_db
        username: admin_user
        password: password
        driver-class-name: org.postgresql.Driver

# JPA Configuration
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        properties:
            hibernate:
                show-sql: true


    flyway:
        baseline-on-migrate: true
        default-schema: public
        schemas: public
        baseline-version: 0